Migrate to TypeScript
editor-js/paragraph pull request #83
Opened 2024-01-16 07:38 UTC by AbdSat

Migrate this project to TypeScript and provide type declarations.

2024-01-17 18:41 UTC, TatianaFomina requested changes
Tried to build and import this version of the plugin, seems like type declarations are still  missing... 

![image](https://github.com/editor-js/paragraph/assets/31101125/4c56ff84-83fc-4637-8582-aaa5135b053d)

2024-01-17 18:41 UTC, TatianaFomina commented on src/index.ts
> +   * @class
seems like `@class` is not needed

2024-01-21 16:37 UTC, TatianaFomina requested changes

2024-01-21 16:37 UTC, TatianaFomina commented on paragraph.d.ts
> +declare module '@editorjs/paragraph';
This file should be generated during build time and should contain all the types. Investigate on ways to do this, maybe use [this vite plugin ](https://github.com/qmhc/vite-plugin-dts)

2024-01-28 17:58 UTC, TatianaFomina requested changes
Doesn't seem to work 🥲

<img width="615" alt="image" src="https://github.com/editor-js/paragraph/assets/31101125/109766c3-c557-40c2-b9e3-98d9415da4ea">

2024-01-28 17:58 UTC, TatianaFomina commented on vite.config.js
> +
```suggestion
```

2024-03-30 13:38 UTC, neSpecc commented
Code Review was not passed

2024-03-30 13:38 UTC, closed without merging